name: esys_flutter_share_plus
description: A Flutter plugin for sharing images & text with other applications. Fork by Innim
version: 2.2.0
homepage: https://github.com/Innim/esys-flutter-share
repository: https://github.com/Innim/esys-flutter-share
issue_tracker: https://github.com/Innim/esys-flutter-share/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9

flutter:
  plugin:
    platforms:
      android:
        package: de.esys.esysfluttershare
        pluginClass: EsysFlutterSharePlugin
      ios:
        pluginClass: EsysFlutterSharePlugin